name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout libvlcjni
        uses: actions/checkout@main
      - name: Setup Git User
        uses: fregante/setup-git-user@main
      - name: Setup libLVC
        run: ./buildsystem/get-vlc.sh
      - name: Compile libVLC
        run: ./buildsystem/compile-libvlc.sh -a arm64
        env:
           MAKEFLAGS: -j8
