name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout libvlcjni
        uses: actions/checkout@main
      - name: Setup libLVC
        run: ./buildsystem/get-vlc.sh && git config --global user.name "GitHub Actions" && git config ---global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Compile libVLC
        run: ./buildsystem/compile-libvlc.sh -a arm64
        env:
           MAKEFLAGS: -j8
